# Generated by Django 3.2.9 on 2021-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreoperation', models.CharField(blank=True, max_length=150, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_de_livraison', models.IntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('mandataire', models.CharField(blank=True, max_length=50, null=True)),
                ('ppi', models.CharField(blank=True, max_length=50, null=True)),
                ('lycee', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_du_marche', models.DateField()),
                ('codeuai', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('etat_d_avancement', models.CharField(blank=True, choices=[('OL', 'Opération Livrée'), ('EC', 'En Chantier'), ('SE', 'Sélection entreprise'), ('S', 'Suspendue'), ('EMO', "Etude de maîtrise d'œuvre")], max_length=50, null=True)),
                ('montant_des_ap_votes_en_meu', models.FloatField(blank=True, null=True)),
                ('cao_attribution', models.DateField()),
                ('latitude', models.DateField()),
                ('maitrise_d_oeuvre', models.CharField(blank=True, max_length=150, null=True)),
                ('mode_de_devolution', models.CharField(blank=True, max_length=150, null=True)),
                ('annee_d_individualisation', models.IntegerField(blank=True, null=True)),
                ('enveloppe_prev_en_meu', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
