# Generated by Django 3.2.9 on 2021-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investements',
            name='etat_d_avancement',
            field=models.CharField(blank=True, choices=[('Opération Livrée', 'Opération Livrée'), ('En Chantier', 'En Chantier'), ('Sélection entreprise', 'Sélection entreprise'), ('Suspendue', 'Suspendue'), ("Etude de maîtrise d'œuvre", "Etude de maîtrise d'œuvre")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investements',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investements',
            name='titreoperation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
