# Generated by Django 3.2.9 on 2021-11-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investements_etat_d_avancement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investements',
            new_name='Investments',
        ),
    ]
