# Generated by Django 3.2.9 on 2021-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rename_investements_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='nombre_de_lots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
