# Generated by Django 3.2.9 on 2021-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investments_nombre_de_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='cao_attribution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='notification_du_marche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
